---
version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pln

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.example
      - ./backend/.env.prod
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BROWSER_BASE_URL=http://localhost:8080/api/v1 # Browser sends to this URL
      - BASE_URL=http://backend:3001/api/v1 # Backend sends to this URL
    depends_on:
      - backend

  proxy:
    image: lscr.io/linuxserver/nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
    volumes:
      - ./data/proxy:/config
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    depends_on:
      - web
      - backend
